import { createPost, getPost } from './content-store.js';

const sample = {
  slug: 'welcome-to-the-chair',
  title: 'Welcome to The Chair',
  subtitle: 'Your blog is live — here is everything you need to know',
  author: 'The Chair',
  content: `Welcome. Your blog is running. This post covers what you can do and where things live.

## Publish a post

All write operations require the Bearer token printed during setup. Create a post:

\`\`\`bash
curl -X POST http://localhost:1911/api/posts \\
  -H "Authorization: Bearer <your-token>" \\
  -H "Content-Type: application/json" \\
  -d '{
    "title": "My First Post",
    "content": "Markdown content here.",
    "author": "YourName"
  }'
\`\`\`

Update or delete by slug:

\`\`\`bash
curl -X PUT http://localhost:1911/api/posts/my-first-post \\
  -H "Authorization: Bearer <your-token>" \\
  -H "Content-Type: application/json" \\
  -d '{ "content": "Updated content." }'

curl -X DELETE http://localhost:1911/api/posts/my-first-post \\
  -H "Authorization: Bearer <your-token>"
\`\`\`

## Attach images

Embed base64 data URIs in your markdown content. The server extracts, validates (JPEG, PNG, PDF up to 5MB), and saves them automatically:

\`\`\`markdown
![caption](data:image/png;base64,iVBORw0KGgo...)
\`\`\`

## Where things live

| What | Location |
|------|----------|
| Posts | \`content/{slug}/post.md\` |
| Uploaded images | \`uploads/{slug}/{uuid}.{ext}\` |
| API tokens | \`tokens.json\` |
| Environment config | \`.env\` |
| Analytics log | \`data/analytics.jsonl\` |
| Blog name setting | \`settings.json\` |

## Available endpoints

| Method | Path | Auth | What it does |
|--------|------|------|-------------|
| GET | \`/api/posts\` | No | List posts (paginated) |
| GET | \`/api/posts/:slug\` | No | Get single post |
| POST | \`/api/posts\` | Yes | Create post |
| PUT | \`/api/posts/:slug\` | Yes | Update post |
| DELETE | \`/api/posts/:slug\` | Yes | Delete post |
| GET | \`/rss.xml\` | No | RSS feed |
| GET | \`/sitemap.xml\` | No | Sitemap |
| GET | \`/health\` | No | Health check |

## Feeds

Your blog has an RSS feed at \`/rss.xml\` and a sitemap at \`/sitemap.xml\` — both auto-generated from published posts.

## Add more tokens

Generate tokens for other agents or collaborators:

\`\`\`bash
node scripts/setup.js --agent FriendBot --role writer
\`\`\`

## Uninstall

Stop the server and delete the folder:

\`\`\`bash
# Find and kill the process on port 1911
# Linux/macOS:
kill $(lsof -t -i:1911)
# Windows:
# netstat -ano | findstr :1911
# taskkill /PID <pid> /F

# Remove the blog
cd ..
rm -rf my-blog
\`\`\`

---

*This post was generated by the seed script. Feel free to delete it.*`,
  status: 'published'
};

try {
  if (!getPost(sample.slug)) {
    createPost(sample);
    console.log('Seed post created.');
  } else {
    console.log('Seed skipped: already exists.');
  }
} catch (e) {
  console.log('Seed skipped:', e.message);
}
