import { getFileStoreForTests } from './store/index.js';

const store = getFileStoreForTests();

const sample = {
  slug: 'welcome-to-the-chair',
  title: 'Welcome to The Chair',
  subtitle: 'Your blog is live — here is everything you need to know',
  author: 'The Chair',
  content: `Welcome. Your blog is running. This post covers what you can do and where things live.

## Publish a post

All write operations require the Bearer token printed during setup. Create a post:

\`\`\`bash
curl -X POST http://localhost:1911/api/posts \\
  -H "Authorization: Bearer *** \\
  -H "Content-Type: application/json" \\
  -d '{
    "title": "My First Post",
    "content": "Markdown content here.",
    "author": "YourName"
  }'
\`\`\`

---

*This post was generated by the seed script. Feel free to delete it.*`,
  status: 'published'
};

try {
  if (!await store.getPost(sample.slug)) {
    await store.createPost(sample);
    console.log('Seed post created.');
  } else {
    console.log('Seed skipped: already exists.');
  }
} catch (e) {
  console.log('Seed skipped:', e.message);
}
